### PR TITLE
Find exact match

### LINKED ISSUE #140: Error in graph
I was very happy today with the new kubeview release using G6 layout. However I was baffled when I ran my OpenTofu deployment and viewed the results in kubeview. It seems I made a serious error while working.

In kubeview 2.1 I saw this:

Image

I checked my IaC definitions, and couldn't fathom how this error could even arise. It should not have been possible. So just to be sure I started kubeview 2.0.4 instead and saw how things really are connected:

Image

> [!NOTE]
> Actually, `customer-portal-ingress` ought to be connected to `customer-portal-service` in kubeview 2.0.4 too, but that's another issue. I suspect kubeview doesn't handle the `default_backend` of the ingress correctly.

So somehow in kubeview 2.1 the ingress - service connection is drawn incorrectly, and the service - deployment connection is drawn incorrectly.

### PR DESCRIPTION
**Pull request by Ghostbird**
Fixes #140 

The `findResByName` function returned the first resource whose name contained the search string.

Now it instead returns the shortest-named resource whose name contains the search string. The assumption is that if there are multiple matches, one is a longer name, that coincidentally also contains the search string, but is not the intended resource. The shortest one is the actual intended match.

There may still be edge cases where this too fails. Especially when you get creative with kubernetes name generation.

### CODE REVIEW

File: public/js/cache.js [hunk 1]
```diff
@@ -61,6 +61,7 @@ export function findResByName(kind, name) {
   const list = Object.values(resMap).filter((res) => {
     return res.kind === kind && res.metadata.name.toLowerCase().includes(name.toLowerCase())
```
Comment (benc-uk) [inline public/js/cache.js:62]:
```suggestion
    return res.kind === kind && res.metadata.name === name
```

**Review by benc-uk — COMMENTED** [review]
I think we can simplify this even more!  
I'll admit I let AI create this function and wasn't paying attention! The logical should be an exact match not some substring or partial
